package multivariate_calibration;

import PLS_MATLAB.PLS_MATLAB;
import com.mathworks.toolbox.javabuilder.MWClassID;
import com.mathworks.toolbox.javabuilder.MWComplexity;
import com.mathworks.toolbox.javabuilder.MWException;
import com.mathworks.toolbox.javabuilder.MWNumericArray;

/**
 * PLS(Partial Least Squares) 偏最小二乘法
 * function [YY]=PLS_Java(X,Y,X1,PC) YY是处理后返回的结果；X是模型的吸光度；Y是模型的化学值；X1是经过预处理的吸光度;PC是主成分数
 * 化学值Y的矩阵的行表示样品数，列表示成分种类数量
 * Created by hsp on 2017/6/14.
 */
public class PLS_Algorithm {
    private double[][] pre_ProcessedSpectrum;
    private Object[] result;
    private double[][] concentration;

    /**
     * B已知，只需要实时吸光度X1作为输入，X,Y,PC都暂时默认为1
     */
    public PLS_Algorithm(double[][] pre_ProcessedSpectrum) throws MWException {
     this.pre_ProcessedSpectrum=pre_ProcessedSpectrum;
     PLS_MATLAB pls=new PLS_MATLAB();
     //set size of matrix
        int[] n={this.pre_ProcessedSpectrum.length,this.pre_ProcessedSpectrum[0].length};
        MWNumericArray matrixOfPre_ProcessedSpectrum=MWNumericArray.newInstance(n, MWClassID.DOUBLE, MWComplexity.REAL);
        /* Set matrix values */
        int[] index = {1, 1};
        for (index[0]= 1; index[0] <= n[0]; index[0]++) {
            for (index[1] = 1; index[1] <= n[1]; index[1]++) {
                //MATLAB中矩阵第一个元素位置为（1,1), Java 二维数组第一个元素位置为（0,0）
                matrixOfPre_ProcessedSpectrum.set(index,this.pre_ProcessedSpectrum[index[0]-1][index[1]-1]);
            }
        }
        //invoke the SNV method generated by MATLAB
        this.result=pls.PLS(1, 1,1,matrixOfPre_ProcessedSpectrum,1);
        //convert the return from MATLAB into two-dimensional double array
        MWNumericArray Result=(MWNumericArray) this.result[0];
        this.concentration=(double[][]) Result.toDoubleArray();
        System.out.println("PLS done");
    }

    /**
     *  get the concentration predicted by PLS
     * @return two-dimensional double array storing the predicted concentration by PLS
     */
    public double[][] getConcentration(){
        return this.concentration;
    }
}
